
### Create container
POST http://localhost:8080/create

### Get all instances
GET http://localhost:8080/allinstances

### Get where
GET http://localhost:8080/whereto?q=ve09iijals


### Pause container
PUT http://localhost:8080/pause
Content-Type: application/json

{
  "container_id": "5b6d601ed013a480bcd02ea7006f187eab64ff1e3acd08620635d951b343ad21",
  "from_host": "fesvx9mv7f"
}

### Unpause container
PUT http://localhost:8080/unpause
Content-Type: application/json

{
  "container_id": "5b6d601ed013a480bcd02ea7006f187eab64ff1e3acd08620635d951b343ad21",
  "from_host": "fesvx9mv7f"
}


### Delete container
DELETE http://localhost:8080/delete
Content-Type: application/json

{
  "container_id": "1216e8b3442ab978aeeaef86474b40bfead333e59374637e071dff5c27b1911f",
  "from_host": "qet2kttq5j"
}

### Delete all containers
DELETE http://localhost:8080/deleteall


